### ISSUE TITLE
Configuration error - Service \"tautulli\"

### ISSUE THREAD

**Issue by Foedii** [ahembree/ansible-hms-docker#13] opened 2022-08-11 08:24 UTC
Hi, when i run the command 
`ansible-playbook -i inventory --connection local hms-docker.yml`

I get this : 

```
PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [docker : Ensure platform agnostic requirements.] *************************
ok: [localhost]

TASK [docker : Ensure previous RHEL Docker packages are absent.] ***************
skipping: [localhost]

TASK [docker : Ensure RHEL required packages.] *********************************
skipping: [localhost]

TASK [docker : Ensure yum-utils.] **********************************************
skipping: [localhost]

TASK [docker : Ensure previous Fedora Docker packages are absent.] *************
skipping: [localhost]

TASK [docker : Ensure Fedora dnf-plugins-core.] ********************************
skipping: [localhost]

TASK [docker : Ensure RHEL Docker repo.] ***************************************
skipping: [localhost]

TASK [docker : Ensure previous Debian Docker packages are absent.] *************
ok: [localhost]

TASK [docker : Ensure Debian Docker requirements.] *****************************
ok: [localhost]

TASK [docker : Ensure Debian Docker GPG Key.] **********************************
ok: [localhost]

TASK [docker : Ensure Debian Docker stable repository.] ************************
ok: [localhost]

TASK [docker : Ensure Docker packages.] ****************************************
ok: [localhost]

TASK [docker : Ensure Docker daemon config] ************************************
skipping: [localhost]

TASK [docker : Ensure docker-compose.] *****************************************
ok: [localhost]

TASK [docker : Ensure docker-compose symlink.] *********************************
changed: [localhost]

TASK [docker : Ensure pip Docker packages.] ************************************
changed: [localhost]

TASK [docker : Ensure Docker service.] *****************************************
ok: [localhost]

TASK [docker : Ensure docker users are in the docker group.] *******************
skipping: [localhost]

TASK [gpu : Ensure Packages] ***************************************************
skipping: [localhost] => (item=tar) 
skipping: [localhost] => (item=bzip2) 
skipping: [localhost] => (item=make) 
skipping: [localhost] => (item=automake) 
skipping: [localhost] => (item=gcc) 
skipping: [localhost] => (item=gcc-c++) 
skipping: [localhost] => (item=vim) 
skipping: [localhost] => (item=pciutils) 
skipping: [localhost] => (item=elfutils-libelf-devel) 
skipping: [localhost] => (item=libglvnd-devel) 
skipping: [localhost] => (item=kernel-devel) 

TASK [gpu : Ensure libnvidia Docker repo] **************************************
skipping: [localhost]

TASK [gpu : Ensure libnvidia experimental Docker repo] *************************
skipping: [localhost]

TASK [gpu : Ensure Nvidia Container Runtime repo] ******************************
skipping: [localhost]

TASK [gpu : Ensure nvidia container runtime experimental repo] *****************
skipping: [localhost]

TASK [gpu : Ensure nvidia-container-runtime apt GPG key] ***********************
skipping: [localhost]

TASK [gpu : Ensure nvidia-container-runtime repo] ******************************
skipping: [localhost]

TASK [gpu : Ensure nvidia-docker apt GPG key] **********************************
skipping: [localhost]

TASK [gpu : Ensure nvidia-docker repo] *****************************************
skipping: [localhost]

TASK [gpu : Verify nvidia-container-runtime-hook is in $PATH] ******************
skipping: [localhost]

TASK [gpu : Exit if nvidia-container-runtime-hook is not in $PATH] *************
skipping: [localhost]

TASK [gpu : Ensure the nvidia-docker2 package] *********************************
skipping: [localhost]

TASK [gpu : Verify CUDA container works] ***************************************
skipping: [localhost]

TASK [gpu : Exit if CUDA container fails] **************************************
skipping: [localhost]

TASK [hmsdocker : Obtain public IP.] *******************************************
ok: [localhost]

TASK [hmsdocker : Ensure paths exists locally.] ********************************
changed: [localhost] => (item=/opt/hms-docker)
changed: [localhost] => (item=/opt/hms-docker/apps)
changed: [localhost] => (item=/media/mox/PLEX2/hms-docker/media_data)
changed: [localhost] => (item=/media/mox/PLEX2/hms-docker/media_data/_library)
skipping: [localhost] => (item=) 

TASK [hmsdocker : NAS base configuration tasks.] *******************************
included: /home/mox/Bureau/ansible-hms-docker-1.2.0/roles/hmsdocker/tasks/nas_local.yml for localhost

TASK [hmsdocker : Using local path] ********************************************
ok: [localhost] => {
    "msg": "Using local path for media files"
}

TASK [hmsdocker : Ensure additional NAS configuration] *************************
skipping: [localhost] => (item=None) 
skipping: [localhost] => (item=None) 
skipping: [localhost]

TASK [hmsdocker : Ensure library folders.] *************************************
changed: [localhost] => (item={'type': 'movies', 'folder_name': 'Movies'})
changed: [localhost] => (item={'type': 'tv_shows', 'folder_name': 'TV_Shows'})

TASK [hmsdocker : Ensure container config directories exist.] ******************
changed: [localhost] => (item={'key': 'traefik', 'value': {'enabled': True, 'proxy_host_rule': 'traefik', 'directory': True, 'traefik': True, 'authentik': False, 'authentik_http_proxy': True}})
changed: [localhost] => (item={'key': 'sonarr', 'value': {'enabled': True, 'proxy_host_rule': 'sonarr', 'directory': True, 'traefik': True, 'authentik': False, 'authentik_http_proxy': True, 'expose_to_public': False}})
changed: [localhost] => (item={'key': 'radarr', 'value': {'enabled': True, 'proxy_host_rule': 'radarr', 'directory': True, 'traefik': True, 'authentik': False, 'authentik_http_proxy': True, 'expose_to_public': False}})
changed: [localhost] => (item={'key': 'bazarr', 'value': {'enabled': True, 'proxy_host_rule': 'bazarr', 'directory': True, 'traefik': True, 'authentik': False, 'authentik_http_proxy': True, 'expose_to_public': False}})
changed: [localhost] => (item={'key': 'transmission', 'value': {'enabled': True, 'proxy_host_rule': 'transmission', 'directory': True, 'traefik': True, 'authentik': False, 'authentik_http_proxy': True, 'expose_to_public': False}})
changed: [localhost] => (item={'key': 'portainer', 'value': {'enabled': True, 'proxy_host_rule': 'portainer', 'directory': True, 'traefik': True, 'authentik': False, 'authentik_http_proxy': False, 'expose_to_public': False}})
changed: [localhost] => (item={'key': 'overseerr', 'value': {'enabled': True, 'proxy_host_rule': 'overseerr', 'directory': True, 'traefik': True, 'authentik': False, 'authentik_http_proxy': True, 'expose_to_public': False}})
changed: [localhost] => (item={'key': 'prowlarr', 'value': {'enabled': True, 'proxy_host_rule': 'prowlarr', 'directory': True, 'traefik': True, 'authentik': False, 'authentik_http_proxy': True, 'expose_to_public': False}})
changed: [localhost] => (item={'key': 'requestrr', 'value': {'enabled': True, 'proxy_host_rule': 'requestrr', 'directory': True, 'traefik': True, 'authentik': False, 'authentik_http_proxy': True, 'expose_to_public': False}})
changed: [localhost] => (item={'key': 'plex', 'value': {'enabled': True, 'proxy_host_rule': 'plex', 'directory': True, 'traefik': True, 'authentik': False, 'authentik_http_proxy': True, 'expose_to_public': False}})
changed: [localhost] => (item={'key': 'tautulli', 'value': {'enabled': True, 'proxy_host_rule': 'tautulli', 'directory': True, 'traefik': True, 'authentik': False, 'authentik_http_proxy': True, 'expose_to_public': False}})
changed: [localhost] => (item={'key': 'nzbget', 'value': {'enabled': True, 'proxy_host_rule': 'nzbget', 'directory': True, 'traefik': True, 'authentik': False, 'authentik_http_proxy': True}})
skipping: [localhost] => (item={'key': 'authentik', 'value': {'enabled': False, 'proxy_host_rule': 'authentik', 'directory': True, 'traefik': True, 'authentik': False, 'authentik_http_proxy': True, 'expose_to_public': False}}) 

TASK [hmsdocker : Ensure Traefik config.] **************************************
changed: [localhost]

TASK [hmsdocker : Ensure Traefik certs directory] ******************************
changed: [localhost]

TASK [hmsdocker : Ensure authentik env] ****************************************
skipping: [localhost]

TASK [hmsdocker : Ensure Outposts directory] ***********************************
skipping: [localhost]

TASK [hmsdocker : Ensure authentik Outpost configs] ****************************
skipping: [localhost] => (item={'key': 'traefik', 'value': {'enabled': True, 'proxy_host_rule': 'traefik', 'directory': True, 'traefik': True, 'authentik': False, 'authentik_http_proxy': True}}) 
skipping: [localhost] => (item={'key': 'sonarr', 'value': {'enabled': True, 'proxy_host_rule': 'sonarr', 'directory': True, 'traefik': True, 'authentik': False, 'authentik_http_proxy': True, 'expose_to_public': False}}) 
skipping: [localhost] => (item={'key': 'radarr', 'value': {'enabled': True, 'proxy_host_rule': 'radarr', 'directory': True, 'traefik': True, 'authentik': False, 'authentik_http_proxy': True, 'expose_to_public': False}}) 
skipping: [localhost] => (item={'key': 'bazarr', 'value': {'enabled': True, 'proxy_host_rule': 'bazarr', 'directory': True, 'traefik': True, 'authentik': False, 'authentik_http_proxy': True, 'expose_to_public': False}}) 
skipping: [localhost] => (item={'key': 'transmission', 'value': {'enabled': True, 'proxy_host_rule': 'transmission', 'directory': True, 'traefik': True, 'authentik': False, 'authentik_http_proxy': True, 'expose_to_public': False}}) 
skipping: [localhost] => (item={'key': 'portainer', 'value': {'enabled': True, 'proxy_host_rule': 'portainer', 'directory': True, 'traefik': True, 'authentik': False, 'authentik_http_proxy': False, 'expose_to_public': False}}) 
skipping: [localhost] => (item={'key': 'overseerr', 'value': {'enabled': True, 'proxy_host_rule': 'overseerr', 'directory': True, 'traefik': True, 'authentik': False, 'authentik_http_proxy': True, 'expose_to_public': False}}) 
skipping: [localhost] => (item={'key': 'prowlarr', 'value': {'enabled': True, 'proxy_host_rule': 'prowlarr', 'directory': True, 'traefik': True, 'authentik': False, 'authentik_http_proxy': True, 'expose_to_public': False}}) 
skipping: [localhost] => (item={'key': 'requestrr', 'value': {'enabled': True, 'proxy_host_rule': 'requestrr', 'directory': True, 'traefik': True, 'authentik': False, 'authentik_http_proxy': True, 'expose_to_public': False}}) 
skipping: [localhost] => (item={'key': 'plex', 'value': {'enabled': True, 'proxy_host_rule': 'plex', 'directory': True, 'traefik': True, 'authentik': False, 'authentik_http_proxy': True, 'expose_to_public': False}}) 
skipping: [localhost] => (item={'key': 'tautulli', 'value': {'enabled': True, 'proxy_host_rule': 'tautulli', 'directory': True, 'traefik': True, 'authentik': False, 'authentik_http_proxy': True, 'expose_to_public': False}}) 
skipping: [localhost] => (item={'key': 'nzbget', 'value': {'enabled': True, 'proxy_host_rule': 'nzbget', 'directory': True, 'traefik': True, 'authentik': False, 'authentik_http_proxy': True}}) 
skipping: [localhost] => (item={'key': 'authentik', 'value': {'enabled': False, 'proxy_host_rule': 'authentik', 'directory': True, 'traefik': True, 'authentik': False, 'authentik_http_proxy': True, 'expose_to_public': False}}) 

TASK [hmsdocker : Ensure docker-compose.yml file.] *****************************
changed: [localhost]

TASK [hmsdocker : Ensure containers defined in compose file.] ******************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Configuration error - Service \"tautulli\" uses an undefined network \"authentik_net\""}

RUNNING HANDLER [hmsdocker : restart traefik] **********************************

PLAY RECAP *********************************************************************
localhost                  : ok=20   changed=8    unreachable=0    failed=1    skipped=26   rescued=0    ignored=0   
```

And most importantly this error that i've no idea how to fix it : 
`fatal: [localhost]: FAILED! => {"changed": false, "msg": "Configuration error - Service \"tautulli\" uses an undefined network \"authentik_net\""}`

If you can help me this would be really appreciated!
Have a nice day!

**Comment by Foedii** [comment] 2022-08-11 08:44
Now i also get this error : 
```
TASK [docker : Ensure Debian Docker stable repository.] ***************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: unknown reason"}
```

**Comment by ahembree** [comment] 2022-08-11 12:29
Your first comment was resolved in https://github.com/ahembree/ansible-hms-docker/commit/2f70e5905544614784e40bc8e75e6757f89c8380, please update your local copy of the repo and try again.

As for the 2nd error about the apt cache, that is specific to the host you are running the playbook against, I don't believe it was caused by this repo and is not an error from this repo. Please see https://itsfoss.com/clear-apt-cache/ for info on clearing the apt cache.

**Comment by Foedii** [comment] 2022-08-11 13:02
Hi thanks for the response, for the first command i'm already using the last version of the repo, i've cloned this one this morning.

**Comment by ahembree** [comment] 2022-08-11 14:42
The template that builds the file, specifically starting at this location for the Tautulli container: https://github.com/ahembree/ansible-hms-docker/blob/bd2fddaf0c951fe9002b80008da40c49ba3c1131/roles/hmsdocker/templates/docker-compose.yml.j2#L784 does not have the `authentik_net` assigned to it either directly or through an `if` statement, which leads me to believe your copy of the repo is out of date.

Please run `git pull` to ensure you're on the latest version of the repo.

**Closed** 2022-08-13 13:09 UTC
Labels: invalid
